name: Workflow for testing artefacts

on:
  workflow_dispatch:

jobs:
  build:
    name: Job for testing artefacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with: 
          name: gios-dist-files
          path: |
            dist 
            package.json 
            node_modules

  deploy: 
    name: Fake deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artefacts    
        uses: actions/download-artifact@v4      
        with: 
            name: gios-dist-files

      - name: Fake deploy
        run: |
          ls 
          echo 'Deployed...'

      

